trigger:
  - none


variables:
  VM_IMAGE_NAME: "ubuntu-latest"
  BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  RESOURCE_GROUP_NAME: $(BRANCH_NAME)-components
  BRANCH_NAME_MAX_LENGTH: 15 # Define maxBranchNameLength here
  
stages:
  - stage: check_and_execute
    jobs:
      - template: .\pipelines\check-branch-name.yml  # Reference the template file
        parameters:
          BRANCH_NAME_MAX_LENGTH: $(BRANCH_NAME_MAX_LENGTH)

  - stage: build_and_deploy
    displayName: Build infrastructure and deploy application components
    jobs:
      - job: deploy
        displayName: Deploy
        pool:
          vmImage: $(VM_IMAGE_NAME)
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "UKSC-Dev(1a2d3dc2-61ba-40ef-ae6b-e100ba1f560f)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az group create --name $(RESOURCE_GROUP_NAME) --location uksouth
                az deployment group create --resource-group $(RESOURCE_GROUP_NAME) --template-file components.bicep